"""blog_media added to Post table

Revision ID: 3d229e6c03a9
Revises: 7f844104f34f
Create Date: 2023-09-17 17:49:08.813982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d229e6c03a9'
down_revision: Union[str, None] = '7f844104f34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('blog_media', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'blog_media')
    # ### end Alembic commands ###
