"""change content field in Comment table

Revision ID: b36eea9c8c47
Revises: 625d7e90d2c4
Create Date: 2023-09-07 23:40:44.350429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36eea9c8c47'
down_revision: Union[str, None] = '625d7e90d2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('comments', 'Content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('Content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
